### ISSUE TITLE
Rayman 1 Playstation USA Tileset Required

### ISSUE THREAD

**Issue by gmrjanghwmaster** [RayCarrot/Ray1Editor#1]
Dream Forest Sega Saturn Version Tileset Please Add
![1 Saturn Version Forest](https://user-images.githubusercontent.com/83871923/123552250-4bbfa980-d7b0-11eb-86aa-77a793e07b0d.png)

Picture City Atari Jaguar OR Prototype Tileset Please Add
![4 Atari Jaguar And Prototype Picture City](https://user-images.githubusercontent.com/83871923/123552252-4cf0d680-d7b0-11eb-9d97-1ab89f3e8ebc.png)

Candy Chateau Strawberry Tileset Please Add
![6 strawberry](https://user-images.githubusercontent.com/83871923/123552253-4cf0d680-d7b0-11eb-8d09-46cde7dd9a66.png)

Tileset Update Please. Is it possible?

**Comment by gmrjanghwmaster** [comment]
Rayman Junior Tileset Dream Forest Band Land Blue Mountains Picture City The Cave OF Skops Candy Chateau Junior Version Tileset Add Please.

**Comment by RayCarrot** [comment]
The tileset available in the editor is the one compiled with the game. I do have plans to in a future update allow you to modify these in the editor, but I'm not sure when that'll happen.
