### ISSUE TITLE
Linux port?

### ISSUE THREAD

**Issue by malespiaut** [RayCarrot/Ray1Editor#3]
Hello,

I'm interested in running your software, but I'm not running Windows, and I'm not familiar enough with C# and .NET to try and port it myself.

Is a Linux port and release feasible?

Best regards.

**Comment by RayCarrot** [comment]
Hi!
Although .NET is cross-platform this app is also made using WPF (for the UI) which is not cross-platform, so sadly enough it's not possible. For now I think the only option would be to run it in some sort of wrapper for Windows applications, but I'm not too familiar with that as I'm only on Windows.
