### ISSUE TITLE
Not saving

### ISSUE THREAD

**Issue by Annon-1** [RayCarrot/Ray1Editor#4]
When I try to save my edit, it says that the "disc.xml" file does not exist.
I'm using the PS1 version.

**Comment by RayCarrot** [comment]
For the PS1 version you need some additional files set up for it to work. To make it easier to work with I've included a pre-packaged version of everything needed here: https://raym.app/ray1editor/
You can simply download that, extract the contents and set the game folder to the decompressed Files folder.
